services:
  trainers-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:5051"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - trainers-network

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db
    networks:
      - trainers-network

networks:
  trainers-network:
    driver: bridge

volumes:
  mongodb-data:
